@startuml LowLevelDesign
top to bottom direction
allow_mixing

package db {
    Class AppDAO {
        + Database db
        + transaction

        + run(sql, params = [])
        + get(sql, params = [])
        + all(sql, params = [])
        + startTransaction()
        + commitTransaction()
        + rollbackTransaction()
    }
}

package api {
    package sku
    package skuItem
    package position
    package test_descriptor
    package test_result
    package user
    package restock_order
    package return_order
    package internal_order
    package item
}